sudo: false
os:
  - linux

language: php

php:
  - '7.1'

services:
  - redis-server
  - mongodb

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - pecl channel-update pecl.php.net
  - composer self-update
  - pecl install mongodb
  - composer install --no-interaction --prefer-source
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate
  - phpenv rehash

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml


after_success:
    - bash <(curl -s https://codecov.io/bash) -t 7f0d0fbd-91c7-4d38-8fd3-080c29f29d7a


